---
tags:
- pdep
- guia1
- basico
- descripciones
- unificación
layout: input_right
editor: code
type: problem
extra_visible: false
manual_evaluation: false
choices: []
name: puedeAndarNuevosSectores
